version: '3.3'

services:

  #
  # Initialize all data directories with correct permissions.
  # This is a workaround for the fact that Docker always creates volumes as root. This could also be done outside
  # docker-compose in a shell script, but it would add yet another manual maintenance step. This way, permissions are
  # set correctly by simply using docker-compose.
  #
  init-volumes:
    image: alpine:latest
    volumes:
      - ./:/faf-stack
    command: sh -c "cd /faf-stack && sh scripts/init-volumes.sh"

  #
  # Coturn server for proxying between players
  # It uses net: "host" for performance reasons.
  #
  coturn:
    image: bprodoehl/turnserver
    env_file: ./config/faf-coturn/faf-coturn.env
    networks:
      - outside

  #
  # FAF MySQL database.
  #
  db:
    build: git://github.com/FAForever/db.git#develop
    image: faforever/faf-db
    user: ${FAF_DB_USER}
    networks:
      backend:
        aliases:
          - "faf-db"
    restart: always
    env_file: ./config/faf-db/faf-db.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data/faf-db:/var/lib/mysql
    depends_on:
      - init-volumes

  #
  # Prometheus exporter for MySQL server metrics.
  #
  mysql-exporter:
    container_name: faf-mysql-exporter
    image: prom/mysqld-exporter:v0.10.0
    networks:
      backend:
        aliases:
          - "faf-mysql-exporter"
    restart: always
    env_file: ./config/faf-mysql-exporter/faf-mysql-exporter.env
    expose:
      - "9104"

  #
  # FAF game server for clients to connect to.
  #
  python-server:
    container_name: faf-python-server
    build: git://github.com/FAForever/server.git#v0.9.2
    image: faforever/faf-python-server
    user: ${FAF_PYTHON_SERVER_USER}
    networks:
      backend:
        aliases:
          - "faf-python-server"
    restart: always
    env_file: ./config/faf-python-server/faf-python-server.env
    volumes:
      - ./config/faf-python-server/faf-server.pem:/code/faf-server.pem
    ports:
      - "8001:8001" # Main client-connection TCP port
      - "6112:6112/udp" # Non-ICE UDP peering ports
      - "30351:30351/udp"
      - "194:194/udp"
      - "3535:3535/udp"
      - "7:7/udp"
      - "53:53/udp"
      - "67:67/udp"
    depends_on:
      - init-volumes
      - db

  #
  # FAF JSON-API to provide data over HTTP.
  #
  java-api:
    container_name: faf-java-api
    image: faforever/faf-java-api:0.8.8
    user: ${FAF_JAVA_API_USER}
    networks:
      backend:
        aliases:
          - "faf-java-api"
    restart: always
    env_file: ./config/faf-java-api/faf-java-api.env
    volumes:
      - ./data/content:/content
      - ./data/faf-java-api/logs:/logs
    expose:
      - "8011" # HTTP Management API
    ports:
      - "8010:8010" # HTTP API
    depends_on:
      - init-volumes
      - db
    # TODO move to Dockerfile
    healthcheck:
      test: "wget -q -O /dev/null http://localhost:8081/management/health"
      interval: 30s
      timeout: 5s
      retries: 3

  #
  # Old implementation of an almost JSON-API conform API.
  #
  python-api:
    build: git://github.com/FAForever/api.git#v0.9.0
    image: faforever/faf-python-api
    command: python run.py -p 80
    user: ${FAF_PYTHON_API_USER}
    networks:
      backend:
        aliases:
          - "faf-python-api"
    depends_on:
      - init-volumes
      - db
    env_file: ./config/faf-python-api/faf-python-api.env
    environment:
      - VIRTUAL_HOST=api.faforever.com
      - FAF_API_ENVIRONMENT=stabler
      - LETSENCRYPT_HOST=api.faforever.com
      - LETSENCRYPT_EMAIL=admin@faforever.com
      - STATSD_SERVER=172.17.0.1:8125
    volumes:
      - /opt/stable/content:/content
    ports:
      - "8093:80"


  #
  # FAF website.
  #
  website:
    container_name: faf-website
    build: git://github.com/FAForever/website.git#v1.1.1.9
    image: faforever/faf-website
    user: ${FAF_WEBSITE_USER}
    restart: always
    env_file: ./config/faf-website/faf-website.env
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "127.0.0.1:8020:3000"

  #
  # Interface to administer Spring Boot applications.
  #
  spring-boot-admin:
    container_name: faf-spring-boot-admin
    image: aetas/spring-boot-admin-docker:1.4.1
    user: ${FAF_SPRING_BOOT_ADMIN_USER}
    env_file: ./config/faf-spring-boot-admin/faf-spring-boot-admin.env
    ports:
      - "127.0.0.1:8030:8080"
    networks:
      backend:
        aliases:
          - "faf-spring-boot-admin"
    # Service currently not in use
    # restart: always
    healthcheck:
      test: "wget -q -O /dev/null http://localhost:8080"
      interval: 30s
      timeout: 5s
      retries: 3

  #
  # Prometheus is a monitoring and alerting tool that scrapes and stores time-series data.
  #
  prometheus:
    container_name: faf-prometheus
    image: prom/prometheus:v1.7.2
    user: ${FAF_PROMETHEUS_USER}
    env_file: ./config/faf-prometheus/faf-prometheus.env
    networks:
      backend:
        aliases:
          - "faf-prometheus"
    restart: always
    ports:
      - "127.0.0.1:9090:9090" # Webinterface
    volumes:
      - ./config/faf-prometheus/faf-prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/faf-prometheus:/prometheus
    depends_on:
      - init-volumes

  #
  # Grafana reads data from Prometheus and draws monitoring dashboards.
  #
  # This image needs to run as root since is changes users inside the container.
  #
  grafana:
    container_name: faf-grafana
    image: grafana/grafana:4.5.1
    restart: always
    networks:
      - backend
    volumes:
      - ./data/faf-grafana:/var/lib/grafana
    depends_on:
      - init-volumes
    env_file: ./config/faf-grafana/faf-grafana.env
    ports:
      - "8090:3000"

  #
  # QAI irc bot
  #
  qai:
    container_name: faf-qai
    build: git://github.com/FAForever/QAI#v1.0
    image: faforever/faf-qai
    user: ${FAF_QAI_USER}
    depends_on:
      - init-volumes
    volumes:
      - ./config/faf-qai:/config
    networks:
      - backend
    restart: always

  #
  # FAF Mumble server.
  #
  murmur:
    container_name: faf-murmur
    build: git://github.com/FAForever/murmur#v1.0
    image: faforever/faf-murmur
    user: ${FAF_MUMBLE_USER}
    networks:
      - backend
    depends_on:
      - db
    restart: always
    env_file: ./config/faf-murmur/faf-murmur.env
    ports:
      - "64738:64738"
      - "64738:64738/udp"

  #
  # The content management system which is still being used as a backend for the website. The website accesses
  # Wordpress over a JSON API plugin.
  #
  wordpress:
    container_name: faf-wordpress
    image: richarvey/nginx-php-fpm:php5
    user: ${FAF_WORDPRESS_USER}
    restart: always
    volumes:
      - ./data/faf-wordpress:/usr/share/nginx/html
    networks:
      backend:
        aliases:
          - "faf-wordpress"
    depends_on:
      - init-volumes
      - db
    env_file: ./config/faf-wordpress/faf-wordpress.env
    ports:
      - "127.0.0.1:8095:80"

  #
  # The new FAF clanapp.
  #
  clanapp:
    container_name: faf-clanapp
    image: dragonfire/clans:1.0.3
    user: ${FAF_CLANAPP_USER}
    networks:
      - backend
    depends_on:
      - db
    restart: always
    env_file: ./config/faf-clanapp/faf-clanapp.env
    ports:
      - "127.0.0.1:8096:8080"

  #
  # FAF phpBB forum software.
  #
  phpbb3:
    container_name: faf-phpbb3
    image: richarvey/nginx-php-fpm:php5
    user: ${FAF_PHPBB3_USER}
    volumes:
      - ./data/faf-phpbb3/phpbb3/www:/usr/share/nginx/html
      - ./data/faf-phpbb3/phpbb3:/usr/share/phpbb3
      - ./config/faf-phpbb3/database.inc.php:/etc/phpbb3/database.inc.php
    networks:
      - backend
    depends_on:
      - init-volumes
      - db
    restart: always
    env_file: ./config/faf-phpbb3/faf-phpbb3.env
    ports:
      - "127.0.0.1:8098:80"

  #
  # Serves static files such as maps, mods, game files etc.
  #
  content:
    container_name: faf-content
    image: richarvey/nginx-php-fpm:php5
    user: ${FAF_CONTENT_USER}
    volumes:
      - ./data/content:/usr/share/nginx/html
    networks:
      - backend
    depends_on:
      - init-volumes
    restart: always
    env_file: ./config/faf-content/faf-content.env
    ports:
      - "127.0.0.1:8091:80"

  #
  # The FAF media wiki.
  #
  wiki:
    container_name: faf-wiki
    image: richarvey/nginx-php-fpm:php5
    user: ${FAF_WIKI_USER}
    restart: always
    networks:
      - backend
    volumes:
      - ./data/faf-wiki:/usr/share/nginx/html
    depends_on:
      - init-volumes
    env_file: ./config/faf-wiki/faf-wiki.env
    ports:
      - "127.0.0.1:8092:80"

  #
  # The legacy update server from which the legacy client gets its update information.
  #
  legacy-updater:
    container_name: faf-legacy-updater
    build: git://github.com/FAForever/legacy-updater.git#v1.0
    image: faforever/faf-legacy-updater
    user: ${FAF_LEGACY_UPDATER_USER}
    restart: always
    volumes:
      - ./data/content:/content
    networks:
      - backend
    depends_on:
      - init-volumes
      - db
    restart: always
    env_file: ./config/faf-legacy-updater/faf-legacy-updater.env
    ports:
      - "9001:9001"

  #
  # The legacy "live replay" server.
  #
  legacy-live-replay-server:
    container_name: faf-legacy-live-replay-server
    build: git://github.com/FAForever/legacy-replay-server.git#v1.1
    image: faforever/faf-legacy-live-replay-server
    user: ${FAF_LEGACY_LIVE_REPLAY_SERVER_USER}
    restart: always
    volumes:
      - ./data/content:/content
    networks:
      - backend
    depends_on:
      - init-volumes
      - db
    restart: always
    env_file: ./config/faf-legacy-live-replay-server/faf-legacy-live-replay-server.env
    ports:
      - "15000:15000"

  #
  # The legacy "secondary server" which does many different things, most of which are being replaced.
  #
  legacy-secondary-server:
    container_name: faf-legacy-secondary-server
    build: git://github.com/FAForever/legacy-secondaryServer.git#v1.0
    image: faforever/faf-legacy-secondary-server
    user: ${FAF_LEGACY_SECONDARY_SERVER_USER}
    restart: always
    volumes:
      - ./data/content:/content
    networks:
      - backend
    depends_on:
      - init-volumes
      - db
    restart: always
    env_file: ./config/faf-legacy-secondary-server/faf-legacy-secondary-server.env
    ports:
      - "11002:11002"

  #
  # A small web tool that allows users to invite themselves into our Slack group.
  #
  slack-invite-automation:
    container_name: faf-slack-invite-automation
    build: git://github.com/FAForever/slack-invite-automation.git#v1.0
    image: faforever/faf-slack-invite-automation
    user: ${FAF_SLACK_INVITE_AUTOMATION_USER}
    env_file: ./config/faf-slack-invite-automation/faf-slack-invite-automation.env
    restart: always
    ports:
      - "3001:3000"

  #
  # IRC <-> Discord bot. Connects IRC's #aeolus to Discord's #aeolus
  #
  discord-irc:
    container_name: faf-discord-irc
    build: git://github.com/FAForever/faf-discord-irc.git#v1.0
    image: faforever/faf-discord-irc
    user: ${FAF_DISCORD_IRC_USER}
    volumes:
      - ./config/faf-discord-irc/config.json:/config/config.json
    restart: always
    depends_on:
      - init-volumes

  #
  # An nginx proxy which exposes FAF services such as the website, the API etc. through HTTP. It does so by listening
  # for docker containers to come online which have the environment variable VIRTUAL_HOST set. Once such a container
  # comes online, it sets up a virtual host which is forwarded to the only exposed port of that service. If multiple
  # ports are exposed, VIRTUAL_PORT can be set to pick one.
  #
  # For more information, see https://github.com/jwilder/nginx-proxy
  #
  nginx:
    container_name: faf-nginx
    image: jwilder/nginx-proxy:0.5.0
    user: ${FAF_NGINX_USER}
    networks:
      - backend
    volumes:
      - ./data/content:/content
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/faf-nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./data/faf-nginx/certs:/etc/nginx/certs:ro
      - ./data/faf-nginx/html:/usr/share/nginx/html
    depends_on:
      - init-volumes
    ports:
      - "80:80"
      - "443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  #
  # An extension of the nginx proxy which converts exposed containers to HTTPS and automatically generates a
  # Let's Encrypt SSL certificate. It does so by listening for docker containers to come online which have the
  # environment variable LETSENCRYPT_HOST and LETSENCRYPT_EMAIL set.
  #
  # For more information, see https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
  #
  nginx-certs:
    container_name: faf-nginx-certs
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.5
    user: ${FAF_NGINX_CERTS_USER}
    env_file: ./config/faf-nginx-certs/faf-nginx-certs.env
    volumes:
      - ./data/faf-nginx/certs:/etc/nginx/certs:rw
      - ./data/faf-nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/faf-nginx/html:/usr/share/nginx/html
    depends_on:
      - init-volumes

  #
  # Temporary avatar management tool.
  #
  jeremy:
    build: git://github.com/FAForever/Jeremy.git#v1.0
    image: faforever/faf-jeremy
    user: ${FAF_JEREMY_USER}
    env_file: ./config/faf-jeremy/faf-jeremy.env
    environment:
      - VIRTUAL_HOST=jeremy.dev.faforever.com
      - FAF_API_ENVIRONMENT=stabler
      - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
      - LETSENCRYPT_HOST=jeremy.dev.faforever.com
      - LETSENCRYPT_EMAIL=admin@faforever.com
    ports:
      - "8099:5000"

networks:
  backend:
    driver: overlay
  outside:
    external:
      name: "host"
