# vim: set ts=2 sw=2 sts=2 et :
irc:
  build: irc
  links:
    - faf-db:db
  ports:
    - "6667:6667"
    - "6697:6697"

mumble:
  build: murmur
  links:
    - faf-db:db
  env_file:
    - /opt/stable/mumble_secrets.env
  ports:
    - "64738:64738"
    - "64738/udp:64738/udp"

app:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/app:/usr/share/nginx/html
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=app.faforever.com
  ports:
    - "8094:80"

coturn:
  image: bprodoehl/turnserver
  net: "host"
  environment:
    - SKIP_AUTO_IP=true
    - EXTERNAL_IP=37.58.123.3

wordpress:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/wordpress:/usr/share/nginx/html
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=faforever.com,www.faforever.com
  ports:
    - "8095:80"

clans:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/clans:/usr/share/nginx/html
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=clans.faforever.com
  ports:
    - "8096:80"

forums:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/forums/phpbb3/www:/usr/share/nginx/html
    - /opt/stable/forums/phpbb3:/usr/share/phpbb3
    - /opt/stable/forums/etc/phpbb3:/etc/phpbb3
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=forums.dev.faforever.com
  ports:
    - "8080:80"

content:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/content:/usr/share/nginx/html
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=content.dev.faforever.com
  ports:
    - "8090:80"

wiki:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/mediawiki:/usr/share/nginx/html
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=wiki.dev.faforever.com
  ports:
    - "8092:80"

faf-db:
  build: https://github.com/FAForever/db.git
  env_file:
    - /opt/stable/db_secrets.env
  volumes:
    - /opt/stable/db:/var/lib/mysql

faf-api:
  build: https://github.com/FAForever/api.git
  links:
    - faf-db:db
  env_file:
    - /opt/stable/api_secrets.env
  environment:
    - VIRTUAL_HOST=api.dev.faforever.com
    - FAF_API_ENVIRONMENT=stabler
  volumes:
    - /opt/stable/content:/content
  ports:
    - "8091:8080"

faf-server:
  build: https://github.com/FAForever/server.git
  volumes:
    - /opt/stable/content:/content
  ulimits:
    nproc: 65535
    nofile:
      soft: 40000
      hard: 80000
  env_file: server_secrets.env
  links:
    - faf-db:db
  ports:
    - "8001:8001"
    - "30351:30351"

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"

