# vim: set ts=2 sw=2 sts=2 et :
irc:
  build: irc
  links:
    - faf-db:db
  ports:
    - "6667:6667"
    - "6697:6697"
    - "6665:6665"
    - "6666:6666"
    - "8067:8067"
    - "7070:7070"
    - "8167:8167"

mumble:
  build: murmur
  links:
    - faf-db:db
  env_file:
    - /opt/stable/mumble_secrets.env
  ports:
    - "64738:64738"
    - "64738/udp:64738/udp"

app:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/app:/usr/share/nginx/html
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=app.faforever.com
  ports:
    - "8094:80"

coturn:
  image: bprodoehl/turnserver
  net: "host"
  environment:
    - SKIP_AUTO_IP=true
    - EXTERNAL_IP=37.58.123.3

wordpress:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/wordpress:/usr/share/nginx/html
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=faforever.com,www.faforever.com,direct.faforever.com
  ports:
    - "8095:80"

clans:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/clans:/usr/share/nginx/html
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=clans.faforever.com
  ports:
    - "8096:80"

forums:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/forums/phpbb3/www:/usr/share/nginx/html
    - /opt/stable/forums/phpbb3:/usr/share/phpbb3
    - /opt/stable/forums/etc/phpbb3:/etc/phpbb3
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=forums.faforever.com
  ports:
    - "8080:80"

content:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/content:/usr/share/nginx/html
  links:
    - faf-db:db
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=content.faforever.com,content.dev.faforever.com,replay.faforever.com
  ports:
    - "8090:80"

wiki:
  image: richarvey/nginx-php-fpm
  volumes:
    - /opt/stable/mediawiki:/usr/share/nginx/html
  environment:
    - TEMPLATE_NGINX_HTML=0
    - VIRTUAL_HOST=wiki.faforever.com
  ports:
    - "8092:80"

faf-db:
  build: https://github.com/FAForever/db.git
  env_file:
    - /opt/stable/db_secrets.env
  volumes:
    - /opt/stable/db:/var/lib/mysql

faf-api:
  build: api
  links:
    - faf-db:db
  env_file:
    - /opt/stable/api_secrets.env
  environment:
    - VIRTUAL_HOST=api.faforever.com,api.dev.faforever.com
    - FAF_API_ENVIRONMENT=stabler
  volumes:
    - /opt/stable/content:/content
  ports:
    - "8091:8080"

faf-server:
  build: server
  volumes:
    - /opt/stable/content:/content
  ulimits:
    nproc: 65535
    nofile:
      soft: 100000
      hard: 200000
  env_file: server_secrets.env
  environment:
    - STATSD_SERVER=172.17.0.1:8125
    - LOBBY_UDP_PORTS=6112,30351,194,7,3535,53,67
  log_driver: syslog
  links:
    - faf-db:db
  ports:
    - "8001:8001"
    - "6112:6112/udp"
    - "30351/udp:30351/udp"
    - "7:7/udp"
    - "194:194/udp"
    - "3535:3535/udp"
    - "53:53/udp"
    - "67:67/udp"

legacy-updater:
  build: legacy-updater
  volumes:
    - /opt/stable/content:/content
  links:
    - faf-db:db
  env_file: server_secrets.env
  ports:
    - "9001:9001"

legacy-livereplayserver:
  build: legacy-replay-server
  volumes:
    - /opt/stable/content:/content
  links:
    - faf-db:db
  env_file: server_secrets.env
  ports:
    - "15000:15000"

legacy-secondaryserver:
  build: legacy-secondaryServer
  volumes:
    - /opt/stable/content:/content
  links:
    - faf-db:db
  env_file: server_secrets.env
  ports:
    - "11002:11002"

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - /opt/stable/vhost.d:/etc/nginx/vhost.d:ro
    - /opt/stable/content:/content
  ports:
    - "80:80"
    - "443:443"

