CONFIGURATION_REFRESH_TIME: 60
LOG_LEVEL: "TRACE"

DB_SERVER: "faf-db"
DB_LOGIN: "faf-python-server"
DB_PASSWORD: "banana"
DB_NAME: "faf_lobby"

ENABLE_METRICS: true

COTURN_HOSTS: ["test.faforever.com"]
COTURN_KEYS: ["banana"]

FAF_POLICY_SERVER_BASE_URL: "http://faf-policy-server:8097"

FORCE_STEAM_LINK: false
# Seconds since epoch
FORCE_STEAM_LINK_AFTER_DATE: 0

QUEUE_POP_TIME_MAX: 60
